import { useState, useMemo } from "react";
import { BarChart, ArrowUpRight } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

export function ROICalculator() {
  const [traffic, setTraffic] = useState(10000);
  const [conversionRate, setConversionRate] = useState(2.0);
  const [ltv, setLtv] = useState(500);
  const [adSpend, setAdSpend] = useState(2000);

  // Growth projections from SEO services (conservative 30% traffic bump over 6 months)
  const trafficGrowthMultiplier = 1.8;
  const croMultiplier = 1.35;

  const currentLeads = traffic * (conversionRate / 100);
  const currentRevenue = currentLeads * ltv;

  const projectedTraffic = traffic * trafficGrowthMultiplier;
  const projectedConvRate = conversionRate * croMultiplier;
  const projectedLeads = projectedTraffic * (projectedConvRate / 100);
  const projectedRevenue = projectedLeads * ltv;

  const revenueDelta = projectedRevenue - currentRevenue;
  
  const formatCurrency = (val: number) => 
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);

  // Generate 12-month projection data
  const chartData = useMemo(() => {
    const data = [];
    for (let month = 1; month <= 12; month++) {
      // S-curve growth simulation
      const progress = month / 12;
      const easeProgress = progress < 0.5 ? 2 * progress * progress : -1 + (4 - 2 * progress) * progress;
      const currentMonthTraffic = traffic + (projectedTraffic - traffic) * easeProgress;
      const currentMonthConv = conversionRate + (projectedConvRate - conversionRate) * easeProgress;
      const currentMonthRev = (currentMonthTraffic * (currentMonthConv / 100)) * ltv;
      
      data.push({
        month: `M${month}`,
        baseline: currentRevenue,
        projected: Math.round(currentMonthRev),
      });
    }
    return data;
  }, [traffic, conversionRate, ltv, projectedTraffic, projectedConvRate, currentRevenue]);

  return (
    <section className="py-32 relative bg-brand-surface overflow-hidden border-t border-brand-border w-full">
      <div className="max-w-7xl mx-auto px-6 md:px-12 relative z-10 w-full">
        
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="flex items-center justify-center gap-2 mb-6 uppercase tracking-[0.3em] text-[10px] font-bold text-brand-accent">
            <span className="w-10 h-[1px] bg-brand-accent"></span>
            <span>Predictive Growth Simulator</span>
            <span className="w-10 h-[1px] bg-brand-accent"></span>
          </div>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-heading font-black leading-tight uppercase tracking-tighter mb-4">
            Forecasting <span className="text-transparent" style={{ WebkitTextStroke: '1px var(--color-brand-blue)' }}>Market Share.</span>
          </h2>
          <p className="text-brand-text-muted font-light">
            Input your current unit economics to simulate the revenue velocity generated by our enterprise SEO architecture over a 12-month trajectory.
          </p>
        </div>

        <div className="glass-panel border-brand-border p-1 shadow-2xl relative w-full rounded-xl overflow-hidden bg-black/60 backdrop-blur-xl">
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-brand-blue to-transparent opacity-50" />
          
          <div className="flex flex-col xl:flex-row">
            {/* Inputs Section */}
            <div className="w-full xl:w-2/5 p-8 lg:p-12 border-b xl:border-b-0 xl:border-r border-brand-border bg-white/[0.02]">
              <div className="flex items-center gap-3 mb-8 border-b border-brand-border pb-4">
                 <BarChart className="w-4 h-4 text-brand-primary" />
                 <h3 className="text-sm font-bold uppercase tracking-widest text-brand-text">
                   Current Baseline
                 </h3>
              </div>
              
              <div className="space-y-8">
                <div>
                  <div className="flex justify-between items-end mb-4">
                    <label className="text-xs uppercase tracking-widest text-brand-text-muted font-bold">Monthly Organic Traffic</label>
                    <span className="font-mono text-xl text-brand-text font-black">{traffic.toLocaleString()}</span>
                  </div>
                  <input 
                    type="range" 
                    min="500" 
                    max="100000" 
                    step="500" 
                    value={traffic} 
                    onChange={(e) => setTraffic(Number(e.target.value))}
                    className="w-full h-1 bg-brand-surface-light appearance-none rounded-none accent-brand-gold touch-manipulation cursor-grab active:cursor-grabbing"
                  />
                </div>

                <div>
                  <div className="flex justify-between items-end mb-4">
                    <label className="text-xs uppercase tracking-widest text-brand-text-muted font-bold">Current Conversion Rate</label>
                    <span className="font-mono text-xl text-brand-text font-black">{conversionRate.toFixed(1)}%</span>
                  </div>
                  <input 
                    type="range" 
                    min="0.1" 
                    max="10" 
                    step="0.1" 
                    value={conversionRate} 
                    onChange={(e) => setConversionRate(Number(e.target.value))}
                    className="w-full h-1 bg-brand-surface-light appearance-none rounded-none accent-brand-gold cursor-grab active:cursor-grabbing"
                  />
                </div>

                <div>
                  <div className="flex justify-between items-end mb-4">
                    <label className="text-xs uppercase tracking-widest text-brand-text-muted font-bold">Avg. Customer LTV</label>
                    <span className="font-mono text-xl text-brand-text font-black">{formatCurrency(ltv)}</span>
                  </div>
                  <input 
                    type="range" 
                    min="50" 
                    max="10000" 
                    step="50" 
                    value={ltv} 
                    onChange={(e) => setLtv(Number(e.target.value))}
                    className="w-full h-1 bg-brand-surface-light appearance-none rounded-none accent-brand-gold cursor-grab active:cursor-grabbing"
                  />
                </div>

                <div>
                  <div className="flex justify-between items-end mb-4">
                    <label className="text-xs uppercase tracking-widest text-brand-text-muted font-bold">Current Ad Spend (Context)</label>
                    <span className="font-mono text-xl text-brand-text font-black">{formatCurrency(adSpend)}</span>
                  </div>
                  <input 
                    type="range" 
                    min="0" 
                    max="50000" 
                    step="500" 
                    value={adSpend} 
                    onChange={(e) => setAdSpend(Number(e.target.value))}
                    className="w-full h-1 bg-brand-surface-light appearance-none rounded-none accent-brand-gold cursor-grab active:cursor-grabbing"
                  />
                </div>
              </div>
            </div>

            {/* Outputs Section */}
            <div className="w-full xl:w-3/5 p-8 lg:p-12 relative overflow-hidden bg-transparent flex flex-col justify-center">
              <div className="absolute top-0 right-0 w-64 h-64 bg-brand-accent/10 blur-[120px] pointer-events-none" />
              
              <h3 className="text-sm font-bold uppercase tracking-widest text-brand-accent mb-8 flex items-center gap-2">
                <ArrowUpRight className="w-4 h-4" /> 12-Month SEO Impact Projection
              </h3>
              
              {/* Chart */}
              <div className="w-full h-[250px] mb-8">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorProjected" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--color-brand-blue)" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="var(--color-brand-blue)" stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorBaseline" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#3f3f46" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="#3f3f46" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                    <XAxis dataKey="month" stroke="rgba(255,255,255,0.3)" fontSize={10} tickLine={false} axisLine={false} />
                    <YAxis stroke="rgba(255,255,255,0.3)" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(value) => `$${(value/1000)}k`} />
                    <Tooltip 
                      contentStyle={{ backgroundColor: '#0a0a0f', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '4px' }}
                      itemStyle={{ color: '#fff', fontSize: '12px' }}
                      labelStyle={{ color: 'rgba(255,255,255,0.5)', fontSize: '10px', textTransform: 'uppercase', marginBottom: '4px' }}
                    />
                    <Area type="monotone" dataKey="baseline" stroke="#a1a1aa" fillOpacity={1} fill="url(#colorBaseline)" name="Baseline Revenue" />
                    <Area type="monotone" dataKey="projected" stroke="var(--color-brand-blue)" fillOpacity={1} fill="url(#colorProjected)" name="Projected SEO Revenue" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>

              <div className="grid grid-cols-2 gap-8 mb-8">
                <div className="bg-white/[0.03] border border-brand-border p-4 rounded bg-gradient-to-br from-brand-text/[0.05] to-transparent">
                  <p className="text-[10px] uppercase tracking-widest text-brand-text-faint font-bold mb-2">Month 12 Traffic</p>
                  <p className="text-3xl font-heading font-black tracking-tight text-brand-text">{Math.round(projectedTraffic).toLocaleString()}</p>
                </div>
                <div className="bg-white/[0.03] border border-brand-border p-4 rounded bg-gradient-to-bl from-brand-text/[0.05] to-transparent">
                  <p className="text-[10px] uppercase tracking-widest text-brand-text-faint font-bold mb-2">Month 12 Leads</p>
                  <p className="text-3xl font-heading font-black tracking-tight text-brand-text">{Math.round(projectedLeads).toLocaleString()}</p>
                </div>
              </div>

              <div className="pt-6 border-t border-brand-border relative">
                <p className="text-[10px] uppercase tracking-widest text-brand-text-faint font-bold mb-2">New Monthly Revenue Delta</p>
                <div className="flex items-baseline gap-4">
                  <span className="text-5xl md:text-6xl font-heading font-black text-transparent bg-clip-text bg-gradient-to-r from-brand-accent via-white to-white drop-shadow-2xl">
                    +{formatCurrency(revenueDelta)}
                  </span>
                </div>
              </div>
              
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
